name: transaction_signing_gateway
description: Transaction Signing gateway
version: 0.0.1
publish_to: 'none' # TODO publish it when ready

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_secure_storage: ^8.0.0
  biometric_storage: ^4.1.3
  encrypt: ^5.0.1
  alan:
    path: ../alan
  uuid: ^3.0.6
  decimal: ^2.3.0
  shared_preferences: ^2.0.12
  cosmos_utils:
    path: ../cosmos_utils


dev_dependencies:
  lint: ^1.5.3
  lints: ^2.0.0
#  flutter_test:
#    sdk: flutter
#  lint: ^1.5.3
#  lints: ^2.0.0
#  very_good_analysis: 3.1.0
#  mocktail: 0.3.0

