- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    # - id: go-vet
    - id: go-lint
    - id: go-imports
    # - id: go-cyclo
    #   args: [-over=15]
    # - id: validate-toml
    # - id: no-go-testing
    # - id: gometalinter
    - id: golangci-lint
    # - id: go-critic
    # - id: go-unit-tests
    # - id: go-build
    - id: go-mod-tidy
- repo: local
  hooks:
    - id: unit-tests
      name: unit tests
      entry: make
      language: system
      args: [unit_tests]
    - id: fixture-unit-tests
      name: fixture unit tests
      entry: make
      language: system
      args: [fixture_unit_tests]