abci = "socket"
chain-id = "pylonschain"
db_backend = "goleveldb"
db_dir = "data"
fast_sync = true
filter_peers = false
genesis_file = "config/genesis.json"
log_format = "plain"
log_level = "main:info,state:info,*:error"
moniker = "node0"
node_key_file = "config/node_key.json"
priv_validator_key_file = "config/priv_validator_key.json"
priv_validator_laddr = ""
priv_validator_state_file = "data/priv_validator_state.json"
prof_laddr = "localhost:6060"
proxy_app = "tcp://127.0.0.1:26658"

[consensus]
  create_empty_blocks = true
  create_empty_blocks_interval = "0s"
  peer_gossip_sleep_duration = "100ms"
  peer_query_maj23_sleep_duration = "2s"
  skip_timeout_commit = false
  timeout_commit = "5s"
  timeout_precommit = "1s"
  timeout_precommit_delta = "500ms"
  timeout_prevote = "1s"
  timeout_prevote_delta = "500ms"
  timeout_propose = "3s"
  timeout_propose_delta = "500ms"
  wal_file = "data/cs.wal/wal"

[fastsync]
  version = "v0"

[instrumentation]
  max_open_connections = 3
  namespace = "tendermint"
  prometheus = false
  prometheus_listen_addr = ":26660"

[mempool]
  broadcast = true
  cache_size = 10000
  max_tx_bytes = 1048576
  max_txs_bytes = 1073741824
  recheck = true
  size = 5000
  wal_dir = ""

[p2p]
  addr_book_file = "config/addrbook.json"
  addr_book_strict = false
  allow_duplicate_ip = false
  dial_timeout = "3s"
  external_address = ""
  flush_throttle_timeout = "100ms"
  handshake_timeout = "20s"
  laddr = "tcp://0.0.0.0:26656"
  max_num_inbound_peers = 40
  max_num_outbound_peers = 10
  max_packet_msg_payload_size = 1024
  persistent_peers = "515a6e4dbd475a440d690ab3abdfdb1297914003@10.107.138.3:26656,fa8d22b1b289cd0a73bd8bcf865f0e365ad83866@10.107.138.4:26656"
  persistent_peers_max_dial_period = "0s"
  pex = true
  private_peer_ids = ""
  recv_rate = 5120000
  seed_mode = false
  seeds = ""
  send_rate = 5120000
  unconditional_peer_ids = ""
  upnp = false

[rpc]
  cors_allowed_headers = ["Origin","Accept","Content-Type","X-Requested-With","X-Server-Time"]
  cors_allowed_methods = ["HEAD","GET","POST"]
  cors_allowed_origins = []
  grpc_laddr = ""
  grpc_max_open_connections = 900
  laddr = "tcp://0.0.0.0:26657"
  max_body_bytes = 1000000
  max_header_bytes = 1048576
  max_open_connections = 900
  max_subscription_clients = 100
  max_subscriptions_per_client = 5
  timeout_broadcast_tx_commit = "10s"
  tls_cert_file = ""
  tls_key_file = ""
  unsafe = false

[tx_index]
  index_all_keys = true
  index_keys = ""
  indexer = "kv"
