name: pylons_wallet
description: Pylons Wallet
publish_to: "none"
version: 1.0.1+142


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2
  modal_bottom_sheet: ^2.0.0
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

  alan: 0.40.2+1
  backdrop: ^0.7.1
  http: ^0.13.4
  shared_preferences: ^2.0.12
  share_plus: 4.0.3
  detectable_text_field: ^2.0.3
  auto_size_text: ^3.0.0

  flutter_svg_provider: 1.0.3

  ## there's a newer version of this that we should migrate to when we have time for the work involved
  flutter_staggered_grid_view: ^0.4.0

  transparent_image: ^2.0.0
  flutter_sticky_header: ^0.6.0
  expandable: 5.0.1

  easy_localization: 3.0.1
  image_picker: 0.8.4+4
  image_cropper: 1.4.1
  popup_menu: ^1.0.5
  cached_network_image: ^3.1.0
  flutter_dotenv: 5.0.2
  permission_handler: 8.3.0
  googleapis: 8.1.0
  google_sign_in: 5.3.0
  icloud_storage: 1.0.0

  # Used for getting applications document directory
  path_provider: 2.0.9

  uni_links: ^0.5.1

  grpc: ^3.0.2

  url_launcher: 6.1.5

  dartz: ^0.10.0

  equatable: ^2.0.3

  internet_connection_checker: ^0.0.1+4

  flutter_secure_storage: 5.0.2

  flutter_screenutil: 5.1.0

  bottom_drawer: ^0.0.3

  # For dependency injection
  get_it: ^7.2.0

  cosmos_ui_components:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/cosmos_ui_components
      ref: main

  cosmos_utils:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/cosmos_utils
      ref: main

  transaction_signing_gateway:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/transaction_signing_gateway
      ref: main

  advance_pdf_viewer:
    git:
      url: https://github.com/lohanidamodar/pdf_viewer.git

  cupertino_icons: ^1.0.3
  decimal: 1.5.0
  uuid: 3.0.5
  fixnum: ^1.0.0
  intl: ^0.17.0
  flutter_stripe: 3.3.0
  webview_flutter: ^3.0.4
  flutter_svg: ^1.0.3
  sprintf: ^6.0.0

  shimmer_animation: ^2.1.0+1

  provider: 6.0.2

  local_auth: 1.1.11

  # Firebase dependencies
  firebase_core: 1.19.2
  firebase_dynamic_links: 4.3.2
  firebase_messaging: 11.4.4
  firebase_remote_config: 2.0.9

  flutter_local_notifications: 9.2.0

  dotted_border: ^2.0.0+2
  just_audio: 0.9.24
  video_player: 2.4.2
  audio_video_progress_bar: 0.10.0
  video_thumbnail: 0.5.0
  just_the_tooltip: 0.0.12

  model_viewer_plus: 1.3.1
  in_app_purchase: 3.0.6

  firebase_crashlytics: 2.8.2
  firebase_app_check: 0.0.6+14

  focus_detector: 2.0.1

  qr_flutter: 4.0.0
  image: 3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  lints: ^1.0.1
  mockito: ^5.0.15
  build_runner: 2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/masks/
    - assets/images/onboarding/
    - assets/images/pages/payment/
    - assets/images/sample_content/
    - assets/images/svg/
    - assets/images/gifs/
    - assets/
    # Don't add assets/images/testing - none of those assets should be in a build
    - env/
    - i18n/en.json
    - i18n/ru.json
    - i18n/id.json
    - i18n/de.json
    - i18n/ko.json
    - i18n/ja.json
    - i18n/es.json
    - i18n/vi.json

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
    - family: PylonsV3
      fonts:
        - asset: assets/fonts/PylonsV3-Condensed.otf
    - family: UniversalSans
      fonts:
        - asset: assets/fonts/UniversalSans-600.ttf
          weight: 600


dependency_overrides:
  webview_flutter_android: "2.8.14"
  alan:
    git:
      url: https://github.com/kjawadDeveloper/alan.dart
      ref: feat/cosmos_0.46
