name: pylons_wallet
description: Pylons Wallet
publish_to: "none"
version: 1.0.1+160


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  advance_pdf_viewer:
    path: pkgs/pdf_viewer-master
  alan:
    path: pkgs/alan
  audio_video_progress_bar: ^0.11.0
  auto_size_text: ^3.0.0
  backdrop: ^0.8.1
  bottom_drawer: ^0.0.3
  cached_network_image: ^3.1.0
  cloud_firestore: ^4.0.2
  cupertino_icons: ^1.0.3

  dartz: ^0.10.1
  decimal: ^2.3.0
  detectable_text_field: ^2.0.3
  dotted_border: ^2.0.0+2
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  expandable: ^5.0.1
  firebase_analytics: ^10.0.2
  firebase_app_check: ^0.1.1+1
  firebase_core: ^2.1.0
  firebase_crashlytics: ^3.0.2
  firebase_dynamic_links: ^5.0.2
  firebase_messaging: ^14.0.2
  firebase_remote_config: ^3.0.2
  fixnum: ^1.0.0
  flappy: ^0.1.7
  floor: ^1.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^12.0.0
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.1
  flutter_screenutil: ^5.5.4
  flutter_secure_storage: ^6.1.0-beta.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_sticky_header: ^0.6.0
  flutter_stripe: ^7.0.0
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.3
  focus_detector: ^2.0.1
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  googleapis: ^9.2.0
  grpc: ^3.0.2
  home_widget: ^0.1.6
  http: ^0.13.4
  icloud_storage: ^2.0.0
  image: ^3.2.0
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  in_app_purchase: ^3.0.7
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  just_audio: ^0.9.29
  just_the_tooltip: 0.0.12
  local_auth: ^2.1.2
  mobx: ^2.0.3
  modal_bottom_sheet: ^2.0.0
  model_viewer_plus:
    path: pkgs/model_viewer_plus.dart-master
  path_provider: ^2.0.11
  permission_handler: ^10.0.1
  popup_menu: ^1.0.5
  provider: ^6.0.3
  qr_flutter: ^4.0.0
  
  share_plus: ^6.0.0
  shared_preferences: ^2.0.12
  shimmer_animation: ^2.1.0+1
  smooth_page_indicator: ^1.0.0+2
  sprintf: ^7.0.0
  transaction_signing_gateway:
    path: pkgs/transaction_signing_gateway
  transparent_image: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  video_player: ^2.4.7
  video_thumbnail: ^0.5.3
  wallpaper: ^1.1.0
  webview_flutter: ^3.0.4
  

dev_dependencies:
  build_runner: ^2.3.2
  # # Revert it for making autogenerated code for database
  # floor_generator: 1.3.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  mockito: ^5.3.2
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/icons/
    - assets/images/masks/
    - assets/images/onboarding/
    - assets/images/pages/payment/
    - assets/images/sample_content/
    - assets/images/svg/
    - assets/images/gifs/
    - assets/
    - env/
    - i18n/en.json
    - i18n/ru.json
    - i18n/id.json
    - i18n/de.json
    - i18n/ko.json
    - i18n/ja.json
    - i18n/es.json
    - i18n/vi.json

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
    - family: PylonsV3
      fonts:
        - asset: assets/fonts/PylonsV3-Condensed.otf
    - family: UniversalSans
      fonts:
        - asset: assets/fonts/UniversalSans-600.ttf
          weight: 600
        - asset: assets/fonts/UniversalSans-750.ttf
          weight: 700



#dependency_overrides:
#  analyzer: 4.1.0
