# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  unit-test:
    docker:
      # specify the version
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/MikeSofaer/pylons
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: GO111MODULE=on make unit_tests
  integration-test:
    docker:
      # specify the version
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/MikeSofaer/pylons
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: GO111MODULE=on go install -v ./cmd/pylonsd/
      - run: GO111MODULE=on go install -v ./cmd/pylonscli/
      - run: pylonsd init --chain-id pylonschain
      - run: make init_accounts
      - run: pylonscli config chain-id pylonschain
      - run: pylonscli config output json
      - run: pylonscli config indent true
      - run: pylonscli config trust-node true
      - run: 
          command: pylonsd start > pylonsd.log & (sleep 5 && GO111MODULE=on make int_tests)
          no_output_timeout: 10m

  fixture-test:
    docker:
      # specify the version
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/MikeSofaer/pylons
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: GO111MODULE=on go install -v ./cmd/pylonsd/
      - run: GO111MODULE=on go install -v ./cmd/pylonscli/
      - run: pylonsd init --chain-id pylonschain
      - run: make init_accounts
      - run: pylonscli config chain-id pylonschain
      - run: pylonscli config output json
      - run: pylonscli config indent true
      - run: pylonscli config trust-node true
      - run: 
          command: pylonsd start > pylonsd.log & (sleep 5 && GO111MODULE=on make fixture_tests)
          no_output_timeout: 10m
workflows:
  version: 2
  build_and_test:
    jobs:
      - unit-test
      - integration-test
      - fixture-test

