name: pylons_wallet
description: Pylons Wallet
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  smooth_page_indicator: ^0.3.0-nullsafety.0
  modal_bottom_sheet: ^2.0.0
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  encrypt: 5.0.1
  alan: 0.40.2+1
  floating_pullup_card: ^1.0.0
  backdrop: 0.6.2
  http: 0.13.3
  shared_preferences: 2.0.6
  resizable_widget: ^1.0.5
  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^1.0.0
  flutter_sticky_header: ^0.6.0
  expandable: ^5.0.1
  getwidget: ^2.0.3
  parent_child_checkbox: ^0.0.3
  easy_localization: ^3.0.0
  image_picker: ^0.8.4+1
  image_cropper: ^1.4.1
  popup_menu: ^1.0.5
  cached_network_image: ^3.1.0
  flutter_dotenv: 5.0.2


  cosmos_ui_components:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/cosmos_ui_components
      ref: main

  cosmos_utils:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/cosmos_utils
      ref: main

  transaction_signing_gateway:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/transaction_signing_gateway
      ref: main

  cupertino_icons: ^1.0.3
  decimal: 1.3.0
  uuid: 3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  flutter_launcher_icons: ^0.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/icon/
    - i18n/en.json
    - i18n/ru.json
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pylons-logo-24x24.png"