name: easel_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+55

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  advance_pdf_viewer:
    path: ../wallet/pkgs/pdf_viewer-master
  audio_video_progress_bar: ^0.11.0
  auto_size_text: 3.0.0
  bottom_drawer: ^0.0.5
  cached_network_image: ^3.1.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  detectable_text_field: ^2.0.4
  device_preview: 1.1.0
  dio: ^4.0.1
  easy_localization: 3.0.1
  equatable: ^2.0.5
  file_picker: ^5.0.1
  firebase_analytics: ^10.0.3
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  fixnum: ^1.0.0
  floor: ^1.3.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.3
  focus_detector: ^2.0.1
  get_it: ^7.2.0  
  google_fonts: ^3.0.1
  image_cropper: ^3.0.0
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  just_audio: ^0.9.28
  media_info: ^0.12.0+1
  model_viewer_plus: ^1.3.2
  path: ^1.8.0
  path_provider: ^2.0.6
  percent_indicator: ^4.2.2
  provider: ^6.0.1
  pylons_sdk:
    path: ../dart_sdk
  share_plus: ^6.0.0  # Used for sharing the NFT link.
  shared_preferences: ^2.0.8
  shimmer_animation: 2.1.0+1
  sqflite: ^2.0.3+1
  steps_indicator: ^1.3.0
  url_launcher: ^6.1.6
  video_player: ^2.4.7

dev_dependencies:
  build_runner: ^2.3.0
  floor_generator: ^1.3.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  mockito: ^5.3.2


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/gifs/
    - assets/images/svg/
    - i18n/en-US.json
    - i18n/ru-RU.json
    - i18n/de.json
    - i18n/es.json

  fonts:
    - family: UniversalSans
      fonts:
        - asset: assets/fonts/UniversalSans-300.ttf
          weight: 300
        - asset: assets/fonts/UniversalSans-400.ttf
          weight: 400
        - asset: assets/fonts/UniversalSans-500.ttf
          weight: 500
        - asset: assets/fonts/UniversalSans-600.ttf
          weight: 600
        - asset: assets/fonts/UniversalSans-750.ttf
          weight: 700


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

