# Updates to this repository are populated downstream
name: Publish protos to pylons_protos repository

on:
  push:
    branches:
      - main

jobs:
  publish-protos:
    name: Publish protos
    runs-on: ubuntu-latest
    environment: production

    steps:
    
     - uses: actions/checkout@v2
      
     - name: Push directory to another repository
       uses: cpina/github-action-push-to-another-repository@main
       env:
        API_TOKEN_GITHUB: ${{ secrets.API_SECRET_GITHUB }}
       with:
        source-directory: 'proto'
        target-directory: 'proto'
        destination-github-username: 'Pylons-tech'
        destination-repository-name: 'pylons_protos'
        user-email: i@pylons.tech
        target-branch: main
